// <auto-generated />
using System;
using KennelIndexer.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KennelIndexer.API.Migrations
{
    [DbContext(typeof(PersonLibraryContext))]
    partial class PersonLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KennelIndexer.API.Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ReasonsForBeingOnTheList")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("05c6c2ab-c63b-4c78-818f-39565d57bcf5"),
                            FirstName = "Thomas",
                            LastName = "Holmegaard"
                        },
                        new
                        {
                            PersonId = new Guid("05c6c2ab-c63b-4c78-818f-39565d57acf5"),
                            Address = "Lollevej 22",
                            FirstName = "Nig",
                            LastName = "Bommer",
                            ReasonsForBeingOnTheList = "Han var pyskopat..."
                        });
                });

            modelBuilder.Entity("KennelIndexer.API.Entities.Picture", b =>
                {
                    b.Property<Guid>("PictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PictureUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PictureId");

                    b.HasIndex("PersonId");

                    b.ToTable("Pictures");

                    b.HasData(
                        new
                        {
                            PictureId = new Guid("c54f132b-79aa-4986-aab4-b0da907ce843"),
                            PersonId = new Guid("05c6c2ab-c63b-4c78-818f-39565d57bcf5"),
                            PictureUri = "located/somewhere/lol.png"
                        });
                });

            modelBuilder.Entity("KennelIndexer.API.Entities.Picture", b =>
                {
                    b.HasOne("KennelIndexer.API.Entities.Person", "Person")
                        .WithMany("Pictures")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
